### ISSUE TITLE
workstyle panics before trying to establish hyprland connection

### ISSUE THREAD

**Issue by krav** [pierrechevalier83/workstyle#49]
On [this line](https://github.com/pierrechevalier83/workstyle/blob/main/src/window_manager.rs#L136), the swayipc socket handler will panic after trying to find the i3 or sway ipc socket. The Hyprland code is never reached.

```[2023-03-24T23:54:44Z ERROR workstyle] panicked at 'internal error: entered unreachable code', /home/krav/.cargo/registry/src/github.com-1ecc6299db9ec823/swayipc-3.0.1/src/socket.rs:17:9```

Setting the path manually causes a different error, but workstyle instead retries the i3 socket connection:
```
# SWAYSOCK=/dev/null /home/krav/.cargo/bin/workstyle
[2023-03-24T23:55:32Z ERROR workstyle] Couldn't connect to WM: Connection refused (os error 111)
[2023-03-24T23:55:33Z ERROR workstyle] Couldn't connect to WM: Connection refused (os error 111)
```

Commenting out the `SwayOrI3::connect()` call will make it work with Hyprland

**Comment by pierrechevalier83** [comment]
I am surprised by this because it means that the sway-rs connection panicked. It's not a behaviour I've seen on my system for some reason.

I would be interested in trying to understand what causes this.

Could you share the output of `i3 --version` and `sway --version`?
Do you even have sway or i3 installed? Maybe the problem is that sway-ipc panics if there isn't any version of these WMs installed.

I'm not opposed to the way you fixed it in PR #52, but I'm concerned that the same bug may hit sway/i3 users who don't have hyprland installed if that's the case, so I'm a bit worried about just merging that.

If I had to pick, I'd rather Hyprland was broken for now than say/i3 since sway/i3 is what people who use workstyle are currently using and getting from the AUR and I prefer to break the new experimental thing than the thing people have already integrated in their workflows if one path must be broken.

I'd like to understand what's happening more precisely and come up with a fix that works for both cases of course.

Note to self: this project is now at a complexity level where I should really bite the bullet and setup some tests for various configurations to make sure it's not so easy to break/regress...

**Comment by krav** [comment]
Oops, that change in #52 was just for me, I didn't mean to include it. But yes, you're right, I'm on NixOS and neither `i3` nor `sway` is in my path. Didn't dig into what the library is doing here, but it panicking trying to exec those to get the IPC socket seems plausible.

**Comment by pierrechevalier83** [comment]
Hi @krav, I've pushed  a potential fix to this issue to main (Fixes it upstream and hotfixes it in workstyle).

Could you try the latest main and let me know whether the crash is gone for you? (I could uninstall Sway and I3 and try it myself, or better, come up with some dockerized way to do it and write some integration tests, but if you have the time to give it a go, It would save me some hassle)

**Comment by krav** [comment]
I tried building `8b4d1cf70798a00ccc30e6ebfc8b9e1c6c52f239` and it's still erroring: 

```
❯ RUST_BACKTRACE=1 target/debug/workstyle
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }

   0: failure::backtrace::internal::InternalBacktrace::new
             at /home/krav/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.8/src/backtrace/internal.rs:46:44
   1: failure::backtrace::Backtrace::new
             at /home/krav/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.8/src/backtrace/mod.rs:121:35
   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from
             at /home/krav/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.8/src/error/error_impl.rs:19:17
   3: <failure::error::Error as core::convert::From<F>>::from
             at /home/krav/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.8/src/error/mod.rs:36:18
   4: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /build/rustc-1.68.2-src/library/core/src/result.rs:2107:27
   5: swayipc::socket::get_path
             at /home/krav/.cargo/registry/src/github.com-1ecc6299db9ec823/swayipc-2.7.2/src/socket.rs:12:18
   6: swayipc::sync::connection::Connection::new
             at /home/krav/.cargo/registry/src/github.com-1ecc6299db9ec823/swayipc-2.7.2/src/sync/connection.rs:15:37
   7: workstyle::main
             at src/main.rs:150:18
   8: core::ops::function::FnOnce::call_once
             at /build/rustc-1.68.2-src/library/core/src/ops/function.rs:250:5
   9: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /build/rustc-1.68.2-src/library/std/src/sys_common/backtrace.rs:121:18
  10: std::rt::lang_start::{{closure}}
             at /build/rustc-1.68.2-src/library/std/src/rt.rs:166:18
  11: std::rt::lang_start_internal
  12: std::rt::lang_start
             at /build/rustc-1.68.2-src/library/std/src/rt.rs:165:17
  13: main
  14: __libc_start_call_main
  15: __libc_start_main_alias_1
  16: _start
', src/main.rs:150:36
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
             at /build/rustc-1.68.2-src/library/core/src/result.rs:1112:23
   4: workstyle::main
             at ./src/main.rs:150:18
   5: core::ops::function::FnOnce::call_once
             at /build/rustc-1.68.2-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

If have nix around something like `nix-shell --pure -p hyprland` should at least remove the i3 and sway binaries from your path. 

Thanks so much for your effort!

**Comment by pierrechevalier83** [comment]
Uhm. I'm surprised you got passed the point where I added the error upstream.

Could you share with me the output of:
```
env  |  grep SOCK
```
?

I suspect you've got either SWAYSOCK or I3SOCK set, so swayipc still attempts to connect to one of these window manager.

**Comment by pierrechevalier83** [comment]
You could also try:
```
SWAYSOCK=/dev/null I3SOCK=/dev/null /home/krav/.cargo/bin/workstyle
```

I think that should work for you now.

**Comment by pierrechevalier83** [comment]
This makes me think that I should add a cli option to pick a specific window manager. If heuristics to say whether or not we should attempt to connect to a WM are not 100% reliable, it may be a good escape hatch for people facing this issue.

**Comment by pierrechevalier83** [comment]
Oh! I think I get it. My upstream PR has a bug. I used `or` which will eagerly call spawn even when we don't want to. I should have used `or_else`... It might not be the only problem, but let me fix that first.

**Comment by pierrechevalier83** [comment]
> Oh! I think I get it. My upstream PR has a bug. I used `or` which will eagerly call spawn even when we don't want to. I should have used `or_else`... It might not be the only problem, but let me fix that first.

I've fixed this in the PR and updated the Cargo.lock.

@krav, I would be interested if you could retry with the latest main when you have a moment, and if it doesn't work, try the steps mentioned above.

I might end up adding the cli option just in case, but I would still be interested in getting to the bottom of this. Ideally, the default behaviour should just work.

**Comment by krav** [comment]
The latest main branch seems to have done the trick! Works well now. 

Still having a command line option is a good idea

**Comment by pierrechevalier83** [comment]
> The latest main branch seems to have done the trick! Works well now.

That's great to hear. Thanks for reporting the issue and for your help reproducing it.

> Still having a command line option is a good idea

I agree. That's in main now :)
